#!/bin/sh

sublime &
gnome-terminal &
google-chrome &
xscreensaver -nosplash &
numlockx on &

amixer set Master 90% unmute
amixer set PCM 85% unmute

sudo xrandr --output HDMI1 --mode 1440x900 --output DP2 --mode 1920x1080 --right-of HDMI1

which fbautostart > /dev/null

if [ $? -eq 0 ]; then
  fbautostart
fi

exec fluxbox
